remove ver check

diff --git a/src/InstallermacOS/scripts/preinstall b/src/InstallermacOS/scripts/preinstall
--- a/src/InstallermacOS/scripts/preinstall
+++ b/src/InstallermacOS/scripts/preinstall
@@ -13,15 +13,15 @@ exit 0
 fi
 
 #  compare the current version against installed version
-if [ $CURRENT_PKG_VERSION = $INSTALLED_PKG_VERSION ] || [ $CURRENT_PKG_VERSION \> $INSTALLED_PKG_VERSION ]
-then
+#if [ $CURRENT_PKG_VERSION = $INSTALLED_PKG_VERSION ] || [ $CURRENT_PKG_VERSION \> $INSTALLED_PKG_VERSION ]
+#then
 #Proceed ffor the installation only if the current package verion is greater than or equal to the installed package version
-echo "Removing previous installation"
-CHROMEHOST_FOLDER=/Library/Google/Chrome/NativeMessagingHosts
-([ -d  ${CHROMEHOST_FOLDER} ] && sudo rm -v "${CHROMEHOST_FOLDER}"/* ) && echo "Files deleted successfully" || echo "Files to delete not found"
-else
+#echo "Removing previous installation"
+#CHROMEHOST_FOLDER=/Library/Google/Chrome/NativeMessagingHosts
+#([ -d  ${CHROMEHOST_FOLDER} ] && sudo rm -v "${CHROMEHOST_FOLDER}"/* ) && echo "Files deleted successfully" || echo "Files to delete not found"
+#else
 #aborting the installation as downgrade is not allowed
-echo "Aborting the installation as the installed package has higher version, downgrade is not allowed"
+#echo "Aborting the installation as the installed package has higher version, downgrade is not allowed"
 # return with error level 1
-exit 1
-fi
+#exit 1
+#fi
